# Generated by Django 5.1.1 on 2024-10-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='comments_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trending',
            name='likes_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trending',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trending',
            name='views_count',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
